### ISSUE TITLE
role "shark" does not exist when starting postgres container

### ISSUE THREAD

**Issue by heptal** [chabala/docker-openmaint#1]
Any idea what this means?

```
postgres_1  | WARNING:  database "cmdbuild" does not exist
postgres_1  | COMMENT
postgres_1  | WARNING:  database "cmdbuild" does not exist
postgres_1  | CREATE SCHEMA
postgres_1  | ALTER SCHEMA
postgres_1  | CREATE SCHEMA
postgres_1  | ERROR:  role "shark" does not exist
postgres_1  | STATEMENT:  ALTER SCHEMA shark OWNER TO shark;
postgres_1  | ERROR:  role "shark" does not exist
dockeropenmaint_postgres_1 exited with code 3
```

I've tried adding `psql -U postgres -c "CREATE ROLE shark;" to`postgres/init-openmaint-postgres.sh` with no success.

**Comment by chabala** [comment]
I am able to replicate the issue with a clean checkout, and I can confirm it's not working as it was previously. Nothing has changed in this repo, nor has the openMAINT distribution changed as near as I can tell.

That leaves the Docker images that this image builds on, postgres and tomcat, both of which have had many changes in the past six months, or perhaps changes in docker-engine and docker-compose themselves. The postgres image seems the most likely culprit.

I will look into it some more.

**Comment by heptal** [comment]
Removing `ADD openmaint-demo.sql /docker-entrypoint-initdb.d/` from `./postgres/Dockerfile` lets it proceed. 

Creating a new database works fine, but using the existing database causes this issue (the vendor is not very helpful. I suppose it's a DB migration for upgrades but for a new install doesn't let you proceed(perhaps it will work by deleting the `.sql` patch files from `WEB-INF/patches/` in the `.war` file but that seems terrible):
http://www.cmdbuild.org/forum/forum-in-english/689293853?set_language=en&cl=en

**Comment by heptal** [comment]
The changes I've made here may assist: https://github.com/chabala/docker-openmaint/compare/master...heptal:master

**Comment by chabala** [comment]
I see how removing the demo database sidesteps the issue, but since the purpose of the image was to load the demo, I'll still need to determine why their database backup isn't loading properly anymore.

Your change to use the postgis image looks like a good idea.

**Comment by heptal** [comment]
It still allows you to select 'demo' from the dropdown which loads a sample internal demo database, but doesn't work with an externally loaded demo database with 'existing' selected. It could be that the demo databases they provide in database/*.backup are out of sync with the current version, but if it worked perviously then I don't know.

And obviously it's ideal to automate deployment with your own custom external demo db, but I haven't yet tried dumping a 'live' working one and loading that via this method.

**Comment by chabala** [comment]
I have managed to further specify the versions of the images I'm building on top of in such a way as to find a happy state for loading the demo database.
